# File: .github/workflows/workflow.yml

on: [push]

name: MyDotNetExample

jobs:

  executesample:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az group list
